### PR TITLE
Update MAINTAINERS.MD

### LINKED ISSUE #2: Update Maintainers.md file
**Problem description**

The new Sandbox Repository has no named Maintainers yet.

**Expected action**

PR against the Maintainers.md file with initial Maintainers for the repository (at least one is recommended).

### PR DESCRIPTION
**Pull request by gmuratk**
#### What type of PR is this?

Add one of the following kinds:

* subproject management

#### Which issue(s) this PR fixes:

Fixes #2, #1, and partially https://github.com/camaraproject/APIBacklog/issues/134

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by eharrison24 — COMMENTED** [review]
Looks good, @gmuratk @lbertz02 and other @camaraproject/admins please review

**Review by hdamker — CHANGES_REQUESTED** [review]
Have invited @lbertz02 to @camaraproject/capabilities-and-runtime-restrictions_codeowners and @camaraproject/capabilities-and-runtime-restrictions_maintainers. As soon as the invite is accepted the CODEOWNERS file will get valid and we are good to go to merge.

**Review by lbertz02 — APPROVED** [review]

**Comment by lbertz02** [comment]
I approved both changes.

**Review by hdamker — APPROVED** [review]

**Comment by lbertz02** [comment]
I like to emphasize what I approve and don't approve of file by file ;)

**Pull request merged**
